[package]
name = "murnion-task-11"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5"
rand = { version = "0.8.4", features = ["std_rng"] }
rodio = "0.14.0"